db:
  image: kartoza/postgis:9.4-2.1
  environment:
    - USERNAME=docker
    - PASS=docker

qgisserver:
  image: kartoza/qgis-server:2.18.10
  hostname: qgis-server
  volumes:
    # Wherever you want to mount your data from
    - ./web:/web
  links:
    - db:db
  ports:
    - "8080:80"

